spring:
  # Data source configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/gradebook_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  # Turn off the Spring Boot banner
  main:
    banner-mode: off
